#!/usr/bin/env python3
# ==========================================================
# 📄 generate_rtm_report.py
# Purpose: Build HTML + PDF report from RTM JSON export
# ==========================================================

import json
import os
import sys
from datetime import datetime
from pathlib import Path

try:
    from fpdf import FPDF
except ImportError:  # fpdf2 is optional
    FPDF = None


def env(name, default=None):
    return os.getenv(name, default)


def load_json(path: str):
    if not os.path.exists(path):
        print(f"[ERROR] JSON file not found: {path}", file=sys.stderr)
        sys.exit(4)
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def build_html(data: dict) -> str:
    test_cases = data.get("testCases", []) or data.get("issues", [])
    execution_key = data.get("executionKey", "")
    project_key = data.get("projectKey", "")
    summary = data.get("summary", "")
    status = data.get("status", "UNKNOWN")
    fetched_at = data.get("fetchedAt", datetime.utcnow().isoformat(timespec="seconds") + "Z")

    rows_html = ""
    for idx, tc in enumerate(test_cases, start=1):
        rows_html += f"""
            <tr>
                <td>{idx}</td>
                <td>{tc.get('key','')}</td>
                <td>{tc.get('name','')}</td>
                <td>{tc.get('status','')}</td>
                <td>{tc.get('executedBy','')}</td>
                <td>{tc.get('executedOn','')}</td>
                <td>{', '.join(tc.get('defects', [])) if isinstance(tc.get('defects'), list) else tc.get('defects','')}</td>
                <td>{tc.get('comment','')}</td>
            </tr>
        """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>RTM Test Execution Report - {execution_key}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 24px;
            color: #222;
        }}
        h1, h2, h3 {{
            color: #1a4f8b;
        }}
        .meta {{
            margin-bottom: 16px;
        }}
        .meta dt {{
            font-weight: bold;
            float: left;
            width: 160px;
        }}
        .meta dd {{
            margin: 0 0 6px 170px;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin-top: 18px;
        }}
        th, td {{
            border: 1px solid #ccc;
            padding: 6px 8px;
            font-size: 12px;
        }}
        th {{
            background: #f4f7fb;
            text-align: left;
        }}
        .status-PASSED {{ background-color: #e6ffed; }}
        .status-FAILED {{ background-color: #ffe6e6; }}
        .status-BLOCKED {{ background-color: #fff6e6; }}
        .footer {{
            margin-top: 32px;
            font-size: 11px;
            color: #777;
        }}
    </style>
</head>
<body>
    <h1>RTM Test Execution Report</h1>
    <h2>{project_key} / {execution_key}</h2>

    <dl class="meta">
        <dt>Summary:</dt><dd>{summary}</dd>
        <dt>Status:</dt><dd>{status}</dd>
        <dt>Project:</dt><dd>{project_key}</dd>
        <dt>Execution:</dt><dd>{execution_key}</dd>
        <dt>Generated at:</dt><dd>{fetched_at}</dd>
        <dt>Total Test Cases:</dt><dd>{len(test_cases)}</dd>
    </dl>

    <h3>Test Case Executions</h3>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Test Case</th>
                <th>Summary</th>
                <th>Status</th>
                <th>Executed By</th>
                <th>Executed On</th>
                <th>Defects</th>
                <th>Comment</th>
            </tr>
        </thead>
        <tbody>
            {rows_html}
        </tbody>
    </table>

    <div class="footer">
        Generated by RTM Jenkins Pipeline on {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")}
    </div>
</body>
</html>
"""
    return html


def build_pdf(data: dict, pdf_path: str):
    if FPDF is None:
        print("[WARN] fpdf2 is not installed – skipping PDF generation.")
        return

    test_cases = data.get("testCases", []) or data.get("issues", [])
    execution_key = data.get("executionKey", "")
    project_key = data.get("projectKey", "")
    status = data.get("status", "UNKNOWN")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, f"RTM Test Execution Report: {project_key} / {execution_key}", ln=True)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f"Overall Status: {status}", ln=True)
    pdf.ln(4)

    # Table header
    pdf.set_font("Arial", "B", 9)
    headers = ["#", "Key", "Summary", "Status", "Exec By", "Exec On"]
    col_widths = [8, 20, 80, 18, 25, 35]

    for header, width in zip(headers, col_widths):
        pdf.cell(width, 7, header, border=1)
    pdf.ln()

    # Rows
    pdf.set_font("Arial", "", 8)
    for idx, tc in enumerate(test_cases, start=1):
        row = [
            str(idx),
            (tc.get("key") or "")[:15],
            (tc.get("name") or "")[:60],
            (tc.get("status") or "")[:10],
            (tc.get("executedBy") or "")[:18],
            (tc.get("executedOn") or "")[:20],
        ]
        for text, width in zip(row, col_widths):
            pdf.cell(width, 6, text, border=1)
        pdf.ln()

    pdf.output(pdf_path)
    print(f"[INFO] PDF report written to {pdf_path}")


def main():
    json_path = env("RTM_OUTPUT_JSON") or "data/rtm_execution.json"
    html_path = env("RTM_REPORT_HTML") or "report/rtm_execution.html"
    pdf_path = env("RTM_REPORT_PDF") or "report/rtm_execution.pdf"

    print(f"[INFO] Loading RTM JSON from {json_path}")
    data = load_json(json_path)

    html = build_html(data)
    Path(os.path.dirname(html_path)).mkdir(parents=True, exist_ok=True)
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"[INFO] HTML report written to {html_path}")

    # Generate PDF as well
    Path(os.path.dirname(pdf_path)).mkdir(parents=True, exist_ok=True)
    build_pdf(data, pdf_path)
    print("[INFO] generate_rtm_report.py completed.")
    sys.exit(0)


if __name__ == "__main__":
    main()
